<?php
/**
 * Created by IntelliJ IDEA.
 * User: leezhang
 * Date: 2020/9/22
 * Time: 2:48 PM
 */

namespace common\modelsext;


use common\helpers\ArrayHelper;
use common\models\SiteJob;
use common\symbol\BaseSymbol;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataProvider;
use yii\helpers\Json;

class SiteJobExt extends SiteJob
{

    public $name_cn;
    public $name_en;

    public function behaviors()
    {
        return [
            'class' => TimestampBehavior::class
        ];
    }

    public function search($params){
        $query = self::find();
        $this->load($params);
        $query->andFilterWhere([
            'in','status',[BaseSymbol::STATUS_NORMAL,BaseSymbol::STATUS_DRAFT]
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20
            ],
            'sort' => [
                'defaultOrder' => [
                    'sort' => SORT_DESC,
                    'created_at' => SORT_DESC
                ]
            ],
        ]);

        return $dataProvider;
    }

    public function attributes()
    {
        return ArrayHelper::merge(parent::attributes(),[
            'name_cn',
            'name_en',
        ]);
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(),[
            'name_cn' => '中文职位',
            'name_en' => '英文职位',
        ]);
    }

    public function rules()
    {
        return [
            [['name_cn','name_en','content'],'required'],
            [['sort','status'],'number']
        ];
    }

    public function scenarios()
    {
        return ArrayHelper::merge(parent::scenarios(),[
            'create' => array_keys($this->attributes),
            'update' => array_keys($this->attributes),
            'delete' => ['status']
        ]);
    }

    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub
        $this->name = Json::encode([
            'cn' => $this->name_cn,
            'en' => $this->name_en
        ]);
    }
}