<?php
/**
 * Created by IntelliJ IDEA.
 * User: leezhang
 * Date: 2018/8/21
 * Time: 下午5:17
 */

namespace backend\components\plupload;

use common\helpers\ArrayHelper;
use backend\components\uploader\QiniuUploader;
use yii\base\Action;
use yii;
use yii\web\Response;

class PluploadAction extends Action
{
    public $config = [];
    public $showUrl;

    public function init(){
        $_config = [
            //上传图片action名字
            'imageActionName' => 'uploadimage',
            //上传图片大小限制，单位B
            'imageMaxSize' => '52428800',
            //上传图片格式限制
            'imageAllowFiles' => [
                ".png",
                ".jpg",
                ".jpeg",
                ".gif",
                ".bmp"
            ],
            //上传图片存放地址
            'imagePath' => 'upload/{yyyy}{mm}{dd}/image/{time}{rand:6}',
            //上传视频action名字
            'videoActionName' => 'uploadvideo',
            //上传视频大小限制，单位B
            'videoMaxSize' => '52428800',
            //上传视频格式限制
            'videoAllowFiles' => [
                ".flv",
                ".swf",
                ".mkv",
                ".avi",
                ".rm",
                ".rmvb",
                ".mpeg",
                ".mpg",
                ".ogg",
                ".ogv",
                ".mov",
                ".wmv",
                ".mp4",
                ".webm",
                ".mp3",
                ".wav",
                ".mid"
            ],
            //上传视频地址
            'videoPath' => 'upload/{yyyy}{mm}{dd}/video/{time}{rand:6}',

            //上传文件action名字
            'fileActionName' => 'uploadfile',
            //上传文件大小限制，单位B
            'fileMaxSize' => '52428800',
            //上传文件格式限制
            'fileAllowFiles' => [
                ".pdf",
                ".doc",
                ".docx",
                ".xls",
                ".xlsx",
                ".pdf",
                ".txt",
                ".rar",
                ".dwg"
            ],
            //上传视频地址
            'filePath' => 'upload/{yyyy}{mm}{dd}/file/{time}{rand:6}',
            'rootPath' => Yii::getAlias('@storage') ? Yii::getAlias('@storage') : $_SERVER['DOCUMENT_ROOT']
        ];

        $this->config = ArrayHelper::merge($_config,$this->config);

        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run()
    {
        if (Yii::$app->request->get('callback',false)) {
            Yii::$app->response->format = Response::FORMAT_JSONP;
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
        }
        return $this->handleAction();
    }

    protected function handleAction(){
        if(Yii::$app->request->isPost){

            if(Yii::$app->user->isGuest){
                $data = [
                    'error' => '用户未登录'
                ];
                echo yii\helpers\Json::encode($data);
                return;
            }
            $this->config['uid'] = Yii::$app->user->id;
            //开始上传
            $file = current($_FILES);
            $ext = is_array($file['name']) ? strtolower(strrchr(current($file['name']),'.')) : strtolower(strrchr($file['name'],'.'));
            if(in_array($ext,$this->config['imageAllowFiles'])){
                $_config = [
                    'uploadAllowFiles' => $this->config['imageAllowFiles'],
                    'uploadAllowSize' => $this->config['imageMaxSize'],
                    'uploadFormatPath' => $this->config['imagePath']
                ];
            }elseif(in_array($ext,$this->config['videoAllowFiles'])) {
                $_config = [
                    'uploadAllowFiles' => $this->config['videoAllowFiles'],
                    'uploadAllowSize' => $this->config['videoMaxSize'],
                    'uploadFormatPath' => $this->config['videoPath']
                ];
            }elseif(in_array($ext,$this->config['fileAllowFiles'])){
                $_config = [
                    'uploadAllowFiles' => $this->config['fileAllowFiles'],
                    'uploadAllowSize' => $this->config['fileMaxSize'],
                    'uploadFormatPath' => $this->config['filePath']
                ];
            }
            else{
                $_config = [
                    'uploadAllowFiles' => '',
                    'uploadAllowSize' => 0,
                    'uploadFormatPath' => null
                ];
                $data = [
                    'error' => '文件类型不允许'
                ];
                echo yii\helpers\Json::encode($data);
                return;
            }

            $this->config = ArrayHelper::merge($_config,$this->config);
            //本地上传
//            $up = new LocalUploader($this->config,'upload');
//            $up->doUp();
//            $fileInfo = $up->getFileInfo();
//
//            if($fileInfo['state'] != 'SUCCESS'){
//                $data = [
//                    'error' => $fileInfo['state']
//                ];
//            }else{
//                $data = [
//                    'url' => Yii::$app->params['storage'] . $this->showUrl . $fileInfo['url']
//                ];
//            }

            //传到七牛
            $ak = Yii::$app->params['qiniu']['ak'];
            $sk = Yii::$app->params['qiniu']['sk'];
            $bucket = Yii::$app->params['qiniu']['bucket'];
            $up = new QiniuUploader($ak,$sk,$bucket);
            $up->load($this->config);
            $res = $up->save();

            if($res['state'] !== 'SUCCESS'){
                $data = [
                    'error' => $res['state']
                ];
            }else{
                $data = [
                    'url' => $res['result']
                ];
            }
            echo yii\helpers\Json::encode($data);
            exit;
        }else{
            $data = [
                'error' => '请求错误'
            ];
            echo yii\helpers\Json::encode($data);
            exit;
        }
    }
}